In [13]:

notas = [100,50,20,10,2]
with open("cedulas.txt", 'r') as f:
    while True:
        valor = int(f.readline())
        if valor == -1:
            break
        print(valor)
        for nota in notas:
            qtd = valor // nota
            valor = valor % nota
            print("{} nota(s) de R${},00" .format(qtd, nota))
    f.close()

130
1 nota(s) de R$100,00
0 nota(s) de R$50,00
1 nota(s) de R$20,00
1 nota(s) de R$10,00
0 nota(s) de R$2,00


In [20]:
listas = []
listona = []

with open("listas.txt", 'r') as f:
    nl = int(f.readline())
    for i in range(nl):
        l = f.readline().split()
        listas.append(l)
        listona += l
    f.close()
unicos = list(set(listona))

print("Todas as listas: {}\n" .format(listas))
print(unicos)
print("Quantidade de elementos distintos: {}" .format(len(unicos)))

dic = {}
for palavra in listona:
    if palavra in dic:
        dic[palavra] += 1
    else:
        dic[palavra] = 1

print("Repetições: {}" .format(dic))

resp = set(listas[0])
for i in range(1, len(listas)):
    resp = resp.intersection(set(listas[i]))

print("Elementos presentes em todas as listas: {}" .format(resp))
        

Todas as listas: [['agua', 'coco', 'mamao', 'mamao', 'coisa'], ['coisa', 'coco', 'mamao', 'credo', 'coisa']]

['coisa', 'coco', 'credo', 'agua', 'mamao']
Quantidade de elementos distintos: 5
Repetições: {'agua': 1, 'coco': 2, 'mamao': 3, 'coisa': 3, 'credo': 1}
Elementos presentes em todas as listas: {'coisa', 'coco', 'mamao'}


In [25]:
with open("texto.txt", 'r') as f:
    texto = f.readline().lower()
    f.close()

consoantes = "bcdfghjklmnpqrstvwxyz"

resp = {}

print(texto)
for letra in texto:
    if letra in consoantes:
        if letra in resp:
            resp[letra] += 1
        else:
            resp[letra] = 1

print(resp)

agua de coco
{'g': 1, 'd': 1, 'c': 2}


In [43]:
import numpy as np

n = int(input())
fi = [1,1]
for i in range(2, n**2):
    fi.append(fi[i-1] + fi[i-2])

fibo = np.array(fi).reshape((n,n))
# print(fi)
print(fibo)

soma = 0
for i in range(n):
    soma += fibo[i,i]
print("A soma da diagonal é: {}" .format(soma))

mult5 = np.sum(fibo % 5 == 0)
print( "A matriz contém {} multiplos de 5" .format(mult5))

transposta = fibo.T[0,:]
print("A primeira linha da sua transposta: {}". format(transposta))

conta3 = np.sum(fibo % 3 == 0, axis = 0)

contagem = np.max(conta3)
posicao = np.argmax(conta3)
print("A linha com maior números múltiplos de  3 é a {} com {} multiplos" .format(posicao, contagem))





[[    1     1     2     3     5]
 [    8    13    21    34    55]
 [   89   144   233   377   610]
 [  987  1597  2584  4181  6765]
 [10946 17711 28657 46368 75025]]
A soma da diagonal é: 79453
A matriz contém 5 multiplos de 5
A primeira linha da sua transposta: [    1     8    89   987 10946]
A linha com maior números múltiplos de  3 é a 3 com 2 multiplos


In [59]:
with open("cartas.txt", 'r') as f:
    while True:
        valor = int(f.readline())
        if valor == 0:
            break
        # print(valor)
        lista = []
        for i in range(1, n+1):
            lista.append(i)
            descarte = []
        while len(lista) >= 2:
            descarte.append(lista.pop(0))
            lista.append(lista.pop(0))
        # print(descarte,lista)
        print("Cartas descartadas: {}" .format(descarte))
        print("Cartas remanescentes: {}" .format(lista))

    f.close()
            

Cartas descartadas: [1, 3, 5, 4]
Cartas remanescentes: [2]
Cartas descartadas: [1, 3, 5, 4]
Cartas remanescentes: [2]
Cartas descartadas: [1, 3, 5, 4]
Cartas remanescentes: [2]
Cartas descartadas: [1, 3, 5, 4]
Cartas remanescentes: [2]


In [82]:
leds = [6,2,5,5,4,5,4,6,3,7,6]

with open("led.txt", 'r') as f:
    nl = int(f.readline())
    for i in range(nl):
        num = f.readline()
        soma = 0
        for i in range(len(num) - 1):
            soma += leds[int(num[i])]
        print("{} leds" .format(soma))

10 leds
4 leds
