In [37]:
a = [1,1,2,23,423,43,33,4,346,4,645,3,2,22,3,42]
list = set(a)

print(list)


# dá pra pegar e fazer isso tbm ao invés de rodar um for, no caso a gente só pega o valor da lista, põe em array e dá um sort()
arr = [list]
arr.sort()
arr


{1, 2, 33, 4, 645, 3, 423, 42, 43, 22, 23, 346}


[{1, 2, 3, 4, 22, 23, 33, 42, 43, 346, 423, 645}]

Lembrar que a lista não repete os números

In [2]:
dic = {}
for i in range(10):
    dic[i] = i ** 2
print(dic)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


Lembrar que o dicionário, quando não tem a posição que você coloca entre chaves, ele cria a posição

In [3]:
array = [1,2,3,4,5,6,7,8,9]
for i in range(len(array)-1,0,-1):
  print("Posição {} = {}".format(i,array[i]))

Posição 8 = 9
Posição 7 = 8
Posição 6 = 7
Posição 5 = 6
Posição 4 = 5
Posição 3 = 4
Posição 2 = 3
Posição 1 = 2


Com o for dá pra rodar ao contrário ;)

In [24]:
aposta_mega_sena = [6, 14, 19, 20, 39, 53]
del aposta_mega_sena[0]
del aposta_mega_sena[0]
aposta_mega_sena

[19, 20, 39, 53]

Dá pra deletar uma posição de uma lista usando o del

In [34]:
meses = ("janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro")
posição = "primeiro","segundo","terceiro","quarto","quinto","sexto","sétimo","oitavo","nono","décimo","décimo primeiro","décimo segundo"
escolha = input("Escolha um mês:")
print(escolha,"é o",posição[meses.index(escolha)],"mês do ano" )

janeiro é o primeiro mês do ano


isso é legal quando queremos associar dados entre duas listas e vetores associando-os pelo index

In [123]:
#leitura de arquivos
with open('teste1.txt', 'r') as f:
  n = int(f.readline())
  # print(n)
  l = []
  for i in range(n):
    line = f.readline()
    l.append(line)
    # print(line)

#escrita em arquivos
with open('saida.txt', 'w') as f:
  for x in l:
    f.write(x)
  f.close()

with open('saida.txt', 'a') as f:
  f.write("\n")
  for x in l:
    
    f.write(x)
  f.close()




with open("saida.txt", 'r') as file:
  n = file.readlines().copy()
  
  for i in range(len(n)):
    for j in range(len(n[i])):
      if n[i][j].isalpha or n[i][j] == '\n' or n[i][j] == ' ':
        continue
      else:
        print(n[i][j])
        print("foi em")

  print(n)

with open("saida.txt", 'r') as file:
    lines = file.readlines().copy()

    for line in lines:
        for char in line:
            if char.isalpha() or char == '\n' or char == ' ':
                continue 
              
            print(char)

    print(lines) 


['1 2 33y\n', '4 5 6\n', '7 8 9\n', '1 2 33y\n', '4 5 6\n', '7 8 9']
1
2
3
3
4
5
6
7
8
9
1
2
3
3
4
5
6
7
8
9
['1 2 33y\n', '4 5 6\n', '7 8 9\n', '1 2 33y\n', '4 5 6\n', '7 8 9']


Tá aí como ler e escrever em arqivos, no exemplo um txt padrão

'a' - começa a escrever no final do arquivo
'w' - escreve no arquivo e se tiver algo já escrito ele limpa o arquivo e escreve
'r' - ler o arquivo

In [39]:
def listas(lista1, lista2):

    listaDeConjuntos = set(lista1), set(lista2)

    ambas = set(lista1).intersection(set(lista2))
    primeiraSomente = set(lista1).difference(set(lista2))
    segundasomente = set(lista2).difference(set(lista1))
    return ambas, primeiraSomente, segundasomente

valor = listas([1,2,3,4], [3,4,5,6])

print("ambas", valor[0])
print("primeira", valor[1])
print("seguda", valor[2])

{3, 4}
{1, 2}


Em conjuntos, temos essas duas funções que pegam tanto a interceção quanto a diferença entre dois conjuntos, além de conseguirmos ter mais de um retorno em uma mesma função

In [1]:
def plus(*args,**kwargs):
  total = 0
  for i in args:
    if "mult" in kwargs.keys():
      total += kwargs["mult"]*i
    else:
      total += i
  return total

# Calcula o somatório de um número qualquer de valores
print(plus(20,30,40,50))
print(plus(20,30,40,50,100,200))
print(plus(20,30,40,50,mult=10))

140
440
1400


Do exemplo anterior, retenha que o parâmetro `*args` mantém uma tupla dos parâmetros não nomeados passados para a função enquanto o `**kwargs` mantém um dicionário dos parâmetros nomeados




Paramentros dinamicos
*Args são argumentos em seu estado bruto
    exemplo:
    strings, inteiros, floats, etc
**Kwargs são variáveis com valores
    exemplo:
    a = 10, b = "Hello World", c = 10.4, etc

In [3]:
x = -11
x.__abs__()

11

pegar o valor absoluto de uma variável

In [4]:
import numpy as np
a = np.zeros((2,2))   # Cria matriz com zeros: no parâmetro deve passar o "shape" desejado como uma tupla
print(a)

b = np.ones((1,2))    # Cria matriz com uns
print(b)

c = np.full((2,2), 7)  # Cria matriz constante
print(c)

d = np.eye(2)         #Cria matriz identidade 2x2
print(d)

e = np.random.random((2,2))  # Cria matriz com números aleatórios entre 0 e 1
print(e)

f = np.arange(0, 3 * np.pi, 0.1)  # cria um vetor usando range (intervalo): início, fim e passo
print(f)

#random.randint(low, high=None, size=None, dtype=int)
g = np.random.randint(100, high=200, size=20) # cria vetor com números inteiros aleatórios dentro de um intervalo
print(g)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98545452 0.85129149]
 [0.42635378 0.97885427]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4]
[150 103 143 194 141 130 110 154 166 198 104 122 190 100 152 198 193 164
 101 132]


algumas formas de se fazer um array usando a biblioteca Numpy

AVISO: 
- NÃO ESQUECER QUE ESSES ARRAYS SÓ CONTÉM DADOS DE MESMO TIPO!
- ESTRUTURAS MULTIDIMENSIONAIS PRECISAM TER OS MESMOS COMPRIMENTOS 

In [21]:
c = np.array([1,2,3,4])

c,c.astype(float) + 0.3

(array([1, 2, 3, 4]), array([1.3, 2.3, 3.3, 4.3]))

Dá pra fazer Castin nos Numpy Arrays

In [31]:
import numpy as np
import random as ra
matriz = np.array([ra.randint(0,100) for x in range(25)])
matriz = matriz.copy().reshape((5, -1))
print(matriz)

[[61 68  3 57 33]
 [78 57 23 79 71]
 [69 71 72 16 73]
 [ 1 21 51 69 85]
 [94 47 69 71 46]]


Essa é uma maneira fácil de criar um array usando o Numpy

In [ ]:
# The Formula 1 season consists of a series of races, known as Grand Prix, organized by the International Federation of Automobile (FIA). The results of each Grand Prix are combined to determine Pilots\' World Championship. More specifically, for each race some points are distributed to pilots, depending on their classification in the race. At the end of the season, the pilot who has earned the most points is declared the World Champion.

# Formula 1 organizers change constantly the competition rules, aiming to provide more excitement to fans. One rule modified for the 2010 season was the distribution of points in each Grand Prix. Since 2003, the scoring rule rewarded the top eight pilots, according to the following table:


# That is, the winning driver received 10 points, second place received 8 points, and so on. In the 2010 season the top ten will receive points, obeying the following table:


# The change in the scoring system led to much speculation about what would have been the effect to the World Championship in the past if the new score had been used. For example, would Lewis Hamilton have been champion in 2008, considering he and Felipe Massa were separated by just one point? To end the speculation, FIA hired you to write a program that, given the results of each race of a season determines the World Champion for different scoring systems.

# Input

# The input contains several test cases. The first line of a test case contains two integers G and P separated by a blank space, indicating the number of Grand Prix (1 ≤ G ≤ 100) and the number of pilots (1 ≤ P ≤ 100).. Pilots are identified by integers from 1 to P. Each of the following G lines indicates the result of a race, and contains Q integers separated by spaces. On each line, the (i)-th number indicates the order of arrival of pilot i in the race (the first number indicates the order of arrival of a pilot 1 in that race, the second number indicates the order of arrival of pilot 2 in that race and so on). The next line contains a single integer S indicating the number of scoring systems (1 ≤ S ≤ 10), After that, each of the following lines S contains a description of a scoring system. The description of a scoring system begins with an integerK (1 ≤ K ≤ P), indicating the last finishing order to receive points, followed by a blank space, followed by e K integers k0, k1, ... , kn−1 (1 ≤ ki ≤ 100) separated by spaces, indicating the number of points to be assigned (the first integer indicates the points for first place, the second integer indicates the points for second place and so on). The last test case is followed by a line containing only two zeros separated by a blank space.

# Output

# For each scoring system in the input your program must print one line, containing the identifier of the World Champion. If more than one pilot are World Champions (ie, if there is a tie), the line must contain all World Champions, in increasing order of identifier, separated by a space.


#To understand better you can start by main function

def calcular(r, k, q, p):
    result = [] #An array that we'll put the results of the races
    for i in range(p): #Filling the array with zero's, we'll need this after to be the same quantity fo pilots
        result.append(0) #adding the zero

    winners = [] #An array that we'll store all the winners of the RULE,(yes, the rule, for each one we have to calculate the winner of this rule)

    for i in range(len(q)):
        #The logic i used was to get the pilot position at each race and verify if it's less or equal to the k variable(quantity of pilots that will receive the points),                                                                                      
        #FOR EXAMPLE q = [3, 1, 2], the pilot[0] got at the third place, pilot[1] got at the first place...                                                                                             k = 2 and r = [5, 2], the first pilot one get five points and the second one get two                                                                                                  So, the pilot[1] get 5, and pilot[2] get 2 points, then we have to calculate the points of each pilot in each races and sum with is sucessor                                                            
        for j in range(len(q[i])):
            if q[i][j] <= k: 
                result[j] += r[q[i][j] - 1] #calculating the races, for each race and for each pilot it sum its points
                #FOR EXAMPLE: if the pilot one got at third at the first race, and first at the second, it will sum it's points
  
    maxPoints = max(result) #We just want to get the winners, so, it get the maximum point get
   
    for i in range(len(result)): #Now we get the position of the winner pilot and then we add to the array winners
        if result[i] == maxPoints:
            winners.append(i + 1) #this +1 is becouse the variable i goes through 0... and when we want to know the player we don't have player 0, we have the player[0] that is the player position at the array, the players comes from 1 to 100.

    return winners
            

def main():
    tryAgain = True #This is for continuing in the loop trying new cases
    while tryAgain:
        g, p = map(int, input().split()) #g variable is the quantity of races and the p variable is the quantity of pilots

        if g == 0 and p == 0: #end the program
            tryAgain = False
            break


        # q = []

        # for i in range(g):
        #     q.append(input().split())
        #     q[i] = [int(n) for n in q[i]]



        q = [list(map(int, input().split())) for _ in range(g)] #the position of each pilots going through 1 < g < 100. THIS IS NOT THE QUEUE FINISHING ORDER OF PILOTS, IT IS IT'S POSITIONS, so the first value is the pilot[0], the second is the pilot[1] ...

        s = int(input()) #quantity of rules that we'll calculate

        for _ in range(s): #for each rule, we have to calculate all races stored at the variable q
            k, *rules = map(int, input().split()) #the variable k, is the quantity of pilots that will receive points, and the rule variable is all the rules that the program will calculate

            result = calcular(rules, k, q, p) #here we get an array of results

            print(*result) #printing the result of each rule

main()