In [37]:
a = [1,1,2,23,423,43,33,4,346,4,645,3,2,22,3,42]
list = set(a)

print(list)


# dá pra pegar e fazer isso tbn ao invés de rodar um for, no caso a gente só pega o valor da lista, põe em array e dá um sort()
arr = [list]
arr.sort()
arr


{1, 2, 33, 4, 645, 3, 423, 42, 43, 22, 23, 346}


[{1, 2, 3, 4, 22, 23, 33, 42, 43, 346, 423, 645}]

Lembrar que a lista não repete os números

In [2]:
dic = {}
for i in range(10):
    dic[i] = i ** 2
print(dic)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


Lembrar que o dicionário, quando não tem a posição que você coloca entre chaves, ele cria a posição

In [3]:
array = [1,2,3,4,5,6,7,8,9]
for i in range(len(array)-1,0,-1):
  print("Posição {} = {}".format(i,array[i]))

Posição 8 = 9
Posição 7 = 8
Posição 6 = 7
Posição 5 = 6
Posição 4 = 5
Posição 3 = 4
Posição 2 = 3
Posição 1 = 2


Com o for dá pra ir contando ao contrário

In [24]:
aposta_mega_sena = [6, 14, 19, 20, 39, 53]
del aposta_mega_sena[0]
del aposta_mega_sena[0]
aposta_mega_sena

[19, 20, 39, 53]

Dá pra deletar uma posição de uma lista usando o del

In [34]:
meses = ("janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro")
posição = "primeiro","segundo","terceiro","quarto","quinto","sexto","sétimo","oitavo","nono","décimo","décimo primeiro","décimo segundo"
escolha = input("Escolha um mês:")
print(escolha,"é o",posição[meses.index(escolha)],"mês do ano" )

janeiro é o primeiro mês do ano


isso é legal quando queremos associar dados entre duas listas e vetores associando-os pelo index

In [ ]:
#leitura de arquivos
with open('teste1.txt', 'r') as f:
  n = int(f.readline())
  print(n)
  l = []
  for i in range(n):
    line = f.readline()
    l.append(line)
    print(line)

#escrita em arquivos
with open('saida.txt', 'w') as f:
  for x in l:
    f.write(x)
  f.close()

Tá aí como ler e escrever em arqivos, no exemplo um txt padrão

In [39]:
def listas(lista1, lista2):

    listaDeConjuntos = set(lista1), set(lista2)

    ambas = set(lista1).intersection(set(lista2))
    primeiraSomente = set(lista1).difference(set(lista2))
    segundasomente = set(lista2).difference(set(lista1))
    return ambas, primeiraSomente, segundasomente

valor = listas([1,2,3,4], [3,4,5,6])

print("ambas", valor[0])
print("primeira", valor[1])
print("seguda", valor[2])

{3, 4}
{1, 2}


Em conjuntos, temos essas duas funções que pegam tanto a interceção quanto a diferença entre dois conjuntos, além de conseguirmos ter mais de um retorno em uma mesma função

In [1]:
def plus(*args,**kwargs):
  total = 0
  for i in args:
    if "mult" in kwargs.keys():
      total += kwargs["mult"]*i
    else:
      total += i
  return total

# Calcula o somatório de um número qualquer de valores
print(plus(20,30,40,50))
print(plus(20,30,40,50,100,200))
print(plus(20,30,40,50,mult=10))

140
440
1400


Do exemplo anterior, retenha que o parâmetro `*args` mantém uma tupla dos parâmetros não nomeados passados para a função enquanto o `**kwargs` mantém um dicionário dos parâmetros nomeados




Paramentros dinamicos
*Args são argumentos em seu estado bruto
    exemplo:
    strings, inteiros, floats, etc
**Kwargs são variáveis com valores
    exemplo:
    a = 10, b = "Hello World", c = 10.4, etc

In [3]:
x = -11
x.__abs__()

11

pegar o valor absoluto de uma variável

In [4]:
import numpy as np
a = np.zeros((2,2))   # Cria matriz com zeros: no parâmetro deve passar o "shape" desejado como uma tupla
print(a)

b = np.ones((1,2))    # Cria matriz com uns
print(b)

c = np.full((2,2), 7)  # Cria matriz constante
print(c)

d = np.eye(2)         #Cria matriz identidade 2x2
print(d)

e = np.random.random((2,2))  # Cria matriz com números aleatórios entre 0 e 1
print(e)

f = np.arange(0, 3 * np.pi, 0.1)  # cria um vetor usando range (intervalo): início, fim e passo
print(f)

#random.randint(low, high=None, size=None, dtype=int)
g = np.random.randint(100, high=200, size=20) # cria vetor com números inteiros aleatórios dentro de um intervalo
print(g)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98545452 0.85129149]
 [0.42635378 0.97885427]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4]
[150 103 143 194 141 130 110 154 166 198 104 122 190 100 152 198 193 164
 101 132]


algumas formas de se fazer um array usando a biblioteca Numpy

AVISO: 
- NÃO ESQUECER QUE ESSES ARRAYS SÓ CONTÉM DADOS DE MESMO TIPO!
- ESTRUTURAS MULTIDIMENSIONAIS PRECISAM TER OS MESMOS COMPRIMENTOS 

In [21]:
c = np.array([1,2,3,4])

c,c.astype(float) + 0.3

(array([1, 2, 3, 4]), array([1.3, 2.3, 3.3, 4.3]))

Dá pra fazer Castin nos Numpy Arrays

In [37]:
import numpy as np
import random as ra
matriz = np.array([ra.randint(0,100) for x in range(25)])
matriz = matriz.copy().reshape((5, -1))
print(matriz)

[[91 20 87 86 19]
 [18 16 24 72 75]
 [42 38 14 95 84]
 [14 17 15 33  2]
 [84 95  5 41 25]]


Essa é uma maneira fácil de criar um array usando o Numpy